//! Compiles the vendored Piton Tree-sitter parser, which has no Rust bindings,
//! and the Piton prompts in `system-prompts`, which become constants in the
//! application (see `src/baked_prompts.rs`).

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::Path;
use std::process::Command;

use serde_json::{Map, Value};

/// Where the prompts are written.
const PROMPTS: &str = "system-prompts";

/// The prompts last compiled, kept with the source so the application still
/// builds where `piton` isn't installed, as on CI.
const SNAPSHOT: &str = "system-prompts/compiled.json";

fn main() {
    compile_parser();
    compile_prompts();
}

fn compile_parser() {
    let src = Path::new("vendor/tree-sitter-piton/src");

    cc::Build::new()
        .include(src)
        .file(src.join("parser.c"))
        .flag_if_supported("-std=c11")
        .flag_if_supported("-Wno-unused-parameter")
        .flag_if_supported("-Wno-unused-but-set-variable")
        .flag_if_supported("-Wno-trigraphs")
        .compile("tree-sitter-piton");

    println!("cargo:rerun-if-changed={}", src.display());
}

fn compile_prompts() {
    println!("cargo:rerun-if-changed={PROMPTS}");
    let mut files: Vec<_> = std::fs::read_dir(PROMPTS)
        .unwrap_or_else(|err| panic!("could not read {PROMPTS}: {err}"))
        .filter_map(|entry| entry.ok().map(|entry| entry.path()))
        .filter(|path| path.extension().is_some_and(|ext| ext == "pi"))
        .collect();
    files.sort();

    let prompts = match compile_with_piton(&files) {
        Some(prompts) => {
            // Kept up to date for builds without `piton`, written only when it
            // changes so it doesn't set off another build.
            let json = format!("{}\n", serde_json::to_string_pretty(&prompts).unwrap());
            if std::fs::read_to_string(SNAPSHOT).ok().as_deref() != Some(json.as_str()) {
                std::fs::write(SNAPSHOT, json)
                    .unwrap_or_else(|err| panic!("could not write {SNAPSHOT}: {err}"));
            }
            prompts
        }
        None => {
            println!(
                "cargo:warning=`piton` isn't installed, so the prompts come from {SNAPSHOT}, \
                 as last compiled"
            );
            let json = std::fs::read_to_string(SNAPSHOT)
                .unwrap_or_else(|err| panic!("could not read {SNAPSHOT}: {err}"));
            serde_json::from_str(&json)
                .unwrap_or_else(|err| panic!("{SNAPSHOT} isn't valid JSON: {err}"))
        }
    };

    let mut code = String::from("// Generated by build.rs from system-prompts. Don't edit.\n");
    for (anchor, value) in &prompts {
        write_module(&mut code, &snake_case(anchor), value, 0);
    }
    let out = Path::new(&std::env::var("OUT_DIR").unwrap()).join("baked_prompts.rs");
    std::fs::write(out, code).expect("could not write the baked prompts");
}

/// Every file's anchors, compiled by `piton`, or `None` if it isn't
/// installed. A file that doesn't compile fails the build.
fn compile_with_piton(files: &[std::path::PathBuf]) -> Option<BTreeMap<String, Value>> {
    let mut prompts = BTreeMap::new();
    for file in files {
        let output = match Command::new("piton")
            .args(["compile", "--stdout"])
            .arg(file)
            .output()
        {
            Ok(output) => output,
            Err(err) if err.kind() == std::io::ErrorKind::NotFound => return None,
            Err(err) => panic!("could not run `piton compile`: {err}"),
        };
        if !output.status.success() {
            panic!(
                "{} doesn't compile:\n{}{}",
                file.display(),
                String::from_utf8_lossy(&output.stdout),
                String::from_utf8_lossy(&output.stderr)
            );
        }
        let compiled: Map<String, Value> =
            serde_json::from_slice(&output.stdout).unwrap_or_else(|err| {
                panic!(
                    "`piton compile` printed no JSON for {}: {err}",
                    file.display()
                )
            });
        prompts.extend(compiled);
    }
    Some(prompts)
}

/// `value` as a module named `name`: a constant for each piece of text, and a
/// module for each dictionary.
fn write_module(code: &mut String, name: &str, value: &Value, depth: usize) {
    let indent = "    ".repeat(depth);
    let Value::Object(entries) = value else {
        panic!("{name} in {PROMPTS} isn't a dictionary");
    };
    writeln!(code, "{indent}pub mod {name} {{").unwrap();
    for (key, value) in entries {
        match value {
            Value::String(text) => writeln!(
                code,
                "{indent}    pub const {}: &str = {text:?};",
                snake_case(key).to_uppercase()
            )
            .unwrap(),
            Value::Object(_) => write_module(code, &snake_case(key), value, depth + 1),
            _ => panic!("{name}.{key} in {PROMPTS} is neither text nor a dictionary"),
        }
    }
    writeln!(code, "{indent}}}").unwrap();
}

/// `name`, in camel or Pascal case, in snake case.
fn snake_case(name: &str) -> String {
    let mut snake = String::new();
    for (ix, ch) in name.chars().enumerate() {
        if ch.is_uppercase() {
            if ix > 0 {
                snake.push('_');
            }
            snake.extend(ch.to_lowercase());
        } else if ch == '-' {
            snake.push('_');
        } else {
            snake.push(ch);
        }
    }
    snake
}
